name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync Fork
        run: |
          git remote add upstream https://github.com/openscanhub/openscanhub.git
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit
          git push origin main
